exp_name = "hoom_wide_test_offline"

[model]
name = "hoom"
in_channel = 7
in_dim = 64
out_dim = 39
att_context_size = [-1, -1]
num_conformer_layers = 8
encoder_dim = 384
use_dynamic_chunk = false
chunk_candidates = []
hoom_layout = ["ccan", "ccan", "buan", "buan"]
ccan_channels = [64, 128]
freq_pool_sizes = [2, 2]
pre_train = true
pre_train_model = "TODO: fill after training"

[data]
wav_folder_path = "/disk7/zchan/Dataset/Dcase2023/dev/foa_dev_test"
ref_files_dir = "/disk7/zchan/Dataset/Dcase2023/dev/ref_files"
norm_file = "/disk7/zchan/Dataset/Dcase2023/dev/norm_dir/24h_ACS_foa_wts_fromlmdb"
batch_size = 1

[streaming]
mode = "offline"
segment_length_sec = 10.0
hop_length_sec = 10.0
overlap_fusion = false
